### ISSUE TITLE
Exclude a directory from template processing

### ISSUE THREAD

**Issue by BrynCooke** [iomentum/cargo-scaffold#12]
It'd be good if in a template definition we could list directories that should be copied, but not processed by mustache.
This would enable scaffolded projects to also include templates for further scaffolding.
e.g. 
* create web app (main template)
* add page (included in the main template directory, but only activated when calling `cargo-scaffold scaffold templates/add-page`)

**Comment by bnjjj** [comment]
Should be solved in v`0.4.0`
