### ISSUE TITLE
Welcome from an alternative (ffizer)

### ISSUE THREAD

**Issue by davidB** [iomentum/cargo-scaffold#2]
Hi,

I'm the author of [ffizer](https://github.com/ffizer/ffizer) an other template generator, and I would like to know if you were aware of it before starting cargo-scaffold, because they are have lot of common features ?
I added a link to cargo-scaffold into my single wiki page https://github.com/ffizer/ffizer/wiki/Alternatives.

Anyways thanks for using handlerbars_misc_helper (I extracted from ffizer), and feel free to open issue (bug, feature request).

**Comment by bnjjj** [comment]
I didn't know this project, in fact I was only aware about cargo-generate and it didn't fulfill my use cases. Will take a look about your project ! Thanks for sharing !

**Comment by bnjjj** [comment]
Added as alternatives in readme :)
